// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dMaiZmvKdpJ4pWYeCQn3zc
// Component: 1UPYifxPFK6Jai

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_legacy_feed_page_designs.module.css"; // plasmic-import: dMaiZmvKdpJ4pWYeCQn3zc/projectcss
import sty from "./PlasmicOffer2.module.css"; // plasmic-import: 1UPYifxPFK6Jai/css

createPlasmicElementProxy;

export type PlasmicOffer2__VariantMembers = {};
export type PlasmicOffer2__VariantsArgs = {};
type VariantPropType = keyof PlasmicOffer2__VariantsArgs;
export const PlasmicOffer2__VariantProps = new Array<VariantPropType>();

export type PlasmicOffer2__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  slot7?: React.ReactNode;
};
type ArgPropType = keyof PlasmicOffer2__ArgsType;
export const PlasmicOffer2__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5",
  "slot6",
  "slot7"
);

export type PlasmicOffer2__OverridesType = {
  root?: Flex__<"div">;
  image?: Flex__<"div">;
  text?: Flex__<"div">;
  offerH1?: Flex__<"div">;
  offerH12?: Flex__<"div">;
  offerP?: Flex__<"div">;
  aCta?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultOffer2Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot4?: React.ReactNode;
  slot5?: React.ReactNode;
  slot6?: React.ReactNode;
  slot7?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOffer2__RenderFunc(props: {
  variants: PlasmicOffer2__VariantsArgs;
  args: PlasmicOffer2__ArgsType;
  overrides: PlasmicOffer2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"image"}
        data-plasmic-override={overrides.image}
        className={classNames(projectcss.all, sty.image)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__gH3Xl)}>
          {renderPlasmicSlot({
            defaultContents: (
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zK71)}
                displayHeight={"423px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/legacy_feed_page_designs/images/offersvg.svg",
                  fullWidth: 76,
                  fullHeight: 150,
                  aspectRatio: 0.503546
                }}
              />
            ),

            value: args.children
          })}
        </div>
      </div>
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, sty.text)}
      >
        <div
          data-plasmic-name={"offerH1"}
          data-plasmic-override={overrides.offerH1}
          className={classNames(projectcss.all, sty.offerH1)}
        >
          {renderPlasmicSlot({
            defaultContents: "SPECIAL OFFER",
            value: args.slot3,
            className: classNames(sty.slotTargetSlot3)
          })}
        </div>
        <div
          data-plasmic-name={"offerH12"}
          data-plasmic-override={overrides.offerH12}
          className={classNames(projectcss.all, sty.offerH12)}
        >
          {renderPlasmicSlot({
            defaultContents: "FREE VITAMIN AIR",
            value: args.slot4,
            className: classNames(sty.slotTargetSlot4)
          })}
        </div>
        <div
          data-plasmic-name={"offerP"}
          data-plasmic-override={overrides.offerP}
          className={classNames(projectcss.all, sty.offerP)}
        >
          {renderPlasmicSlot({
            defaultContents:
              "Money-Back Guarantee: Better Flavor & Harder Hits or Your Money Back.",
            value: args.slot5,
            className: classNames(sty.slotTargetSlot5)
          })}
        </div>
        <PlasmicLink__
          data-plasmic-name={"aCta"}
          data-plasmic-override={overrides.aCta}
          className={classNames(projectcss.all, projectcss.a, sty.aCta)}
          component={Link}
          href={(() => {
            try {
              return $ctx.fetchedData.records[0].fields["Step 2 URL"];
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          onClick={async event => {
            const $steps = {};

            $steps["setVariable"] = true
              ? (() => {
                  const actionArgs = {};
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;
                    undefined;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["setVariable"] != null &&
              typeof $steps["setVariable"] === "object" &&
              typeof $steps["setVariable"].then === "function"
            ) {
              $steps["setVariable"] = await $steps["setVariable"];
            }
          }}
          platform={"nextjs"}
        >
          {renderPlasmicSlot({
            defaultContents: "CLAIM FREE PODS \ud83d\udc49",
            value: args.slot7,
            className: classNames(sty.slotTargetSlot7)
          })}
        </PlasmicLink__>
        <div className={classNames(projectcss.all, sty.freeBox__lSwrd)}>
          {renderPlasmicSlot({
            defaultContents: "CHOOSE FLAVOR",
            value: args.slot6,
            className: classNames(sty.slotTargetSlot6)
          })}
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__rzTg3)}>
          <div className={classNames(projectcss.all, sty.freeBox__eyCzK)}>
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__oKiwh)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"60px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/legacy_feed_page_designs/images/labelsvg.svg",
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tWzt6
                    )}
                  >
                    {"Strawberry"}
                  </div>
                </React.Fragment>
              ),
              value: args.slot
            })}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jzh69)}>
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6QlkF)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"60px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/legacy_feed_page_designs/images/labelsvg2.svg",
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f7Dfn
                    )}
                  >
                    {"Vanilla"}
                  </div>
                </React.Fragment>
              ),
              value: args.slot2
            })}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "image", "text", "offerH1", "offerH12", "offerP", "aCta"],
  image: ["image"],
  text: ["text", "offerH1", "offerH12", "offerP", "aCta"],
  offerH1: ["offerH1"],
  offerH12: ["offerH12"],
  offerP: ["offerP"],
  aCta: ["aCta"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  image: "div";
  text: "div";
  offerH1: "div";
  offerH12: "div";
  offerP: "div";
  aCta: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOffer2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOffer2__VariantsArgs;
    args?: PlasmicOffer2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOffer2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOffer2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOffer2__ArgProps,
          internalVariantPropNames: PlasmicOffer2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOffer2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOffer2";
  } else {
    func.displayName = `PlasmicOffer2.${nodeName}`;
  }
  return func;
}

export const PlasmicOffer2 = Object.assign(
  // Top-level PlasmicOffer2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    image: makeNodeComponent("image"),
    text: makeNodeComponent("text"),
    offerH1: makeNodeComponent("offerH1"),
    offerH12: makeNodeComponent("offerH12"),
    offerP: makeNodeComponent("offerP"),
    aCta: makeNodeComponent("aCta"),

    // Metadata about props expected for PlasmicOffer2
    internalVariantProps: PlasmicOffer2__VariantProps,
    internalArgProps: PlasmicOffer2__ArgProps
  }
);

export default PlasmicOffer2;
/* prettier-ignore-end */
